name: Fragment Check
on: [pull_request]

jobs:
  fragment-check:
    name: Fragment check
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check changelog fragment exists
        run: |
          PR_NUMBER=${{ github.event.number }}

          if [ -n "$(compgen -G "fragments/${PR_NUMBER}.*.md")" ]; then
            echo "Fragment exists"
            exit 0
          fi

          echo "Fragment does not exist"
          exit 1
